### ISSUE TITLE
Question: use of strftime in project

### ISSUE THREAD

**Issue by cleidigh** [thdoan/strftime#2]
@thdoan 
Hello !

I came across your library while working on replacement for a deprecated Firefox function toLocaleFormat()

Your library is excellent and tiny!
Any problem using for a Thunderbird add-on?  I will of course give attribution in the contributor section of the manifest.  I think the license mixing with the Mozilla license should be okay.

Cheers and thanks in advance.
@cleidigh

**Comment by thdoan** [comment]
Sure, have at it! I'm happy to know someone besides myself using my plug-in ^^.

**Comment by cleidigh** [comment]
@thdoan 
Excellent, appreciate the quick response 👍
