### ISSUE TITLE
FEATURE REQUEST: support for abbreviated timezone

### ISSUE THREAD

**Issue by githorse** [thdoan/strftime#4]
Love this library! I use it all the time in preference to what I consider the incomprehensible and poorly-documented Javascript Date formatters. But the one thing I *can't* do is get the abbreviate timezone, which I basically always want. The `strftime` `%Z` option supposedly returns "the timezone name or abbreviation," which are two very different strings -- e.g. `"Eastern Daylight Time"` vs `"EDT"`. In practice, it always seems to be the longer version, but either way, since I can't rely on the output, the `%Z` is worthless to me (and I would imagine the majority of web developers). 

The same issue of course occurs in the Unix `strftime` -- the problem doesn't originate with this library.

So I end up writing my own ugly wrappers around `strftime` to stitch this in everywhere:

```
export function shortTz(date?: Date | null): string | undefined {
  if (!date) { return undefined }
  const timeString = date.toLocaleTimeString('en', {timeZoneName: 'short'})
  return timeString.match(' ([A-Z+0-9]+)$')![1]!
}

export function formatTimeWithShortTz(format: string, time: Date): string {
  return `${stftime(format, time)} ${shortTz(time)}`
}
```

Though `strftime` is intended to be a port of the Unix version, this one simple enhancement to me vastly increases its usefulness. Would it be possible to extend it to cover this case, with the understanding that abbreviations aren't standardized and may be browser-dependent? Since `%Z` is non-deterministic anyway, changing it return the abbreviated time zone (which seems more useful and common than the spelled-out one) would not break backwards compatibility. Ideally we could add a second `%something` for the spelled-out case and cover both.

**Comment by thdoan** [comment]
Hi, thanks for the feature suggestion. IMHO we should leave `%Z` the way it is since I don't know how many people are relying on the fully spelled out version. However, I'm open to adding another option for time zone abbreviation. We can call this option `%Zs` or `%Za` -- what do you think?
